- match:
    dependency_name: FakeItEasy
    update_type: all

- match:
    dependency_name: FluentValidation
    update_type: all

- match:
    dependency_name: Fody
    update_type: all

- match:
    dependency_name: GitVersionTask
    update_type: all

- match:
    dependency_name: Janitor.Fody
    update_type: all

- match:
    dependency_name: McMaster.Extensions.CommandLineUtils
    update_type: all

- match:
    dependency_name: Microsoft.AspNetCore.Server.Kestrel
    update_type: all

- match:
    dependency_name: Microsoft.AspNetCore.StaticFiles
    update_type: all

- match:
    dependency_name: Microsoft.Build.Utilities.Core
    update_type: all

- match:
    dependency_name: Microsoft.DotNet.Analyzers.Compatibility
    update_type: all

- match:
    dependency_name: Microsoft.NET.Test.Sdk
    update_type: all

- match:
    dependency_name: Microsoft.PowerShell.5.ReferenceAssemblies
    update_type: all

- match:
    dependency_name: Microsoft.SourceLink.GitHub
    update_type: all

- match:
    dependency_name: Mono.Cecil
    update_type: all

- match:
    dependency_name: Moq
    update_type: all

- match:
    dependency_name: NuDoq
    update_type: all

- match:
    dependency_name: NUnit3TestAdapter
    update_type: all

- match:
    dependency_name: Obsolete.Fody
    update_type: all

- match:
    dependency_name: Particular.Approvals
    update_type: all

- match:
    dependency_name: Particular.Packaging
    update_type: all

- match:
    dependency_name: Particular.PlatformSample.ServiceControl
    update_type: all

- match:
    dependency_name: Particular.PlatformSample.ServicePulse
    update_type: all

- match:
    dependency_name: PublicApiGenerator
    update_type: all

- match:
    dependency_name: SimpleJson
    update_type: all

- match:
    dependency_name: System.Diagnostics.PerformanceCounter
    update_type: all

- match:
    dependency_name: xunit
    update_type: all

- match:
    dependency_name: xunit.runner.visualstudio
    update_type: all
