# Configuration for probot-stale - https://github.com/probot/stale
only: pulls
daysUntilStale: 30
daysUntilClose: 7
exemptLabels:
  - dependencies
staleLabel: stale
markComment: >
  This pull request has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
limitPerRun: 30
