#nullable enable

namespace NServiceBus.Core.Analyzer.Utility;

using System.Reflection;

static class SourceWriterExtensions
{
    extension(SourceWriter writer)
    {
        public SourceWriter PreAmble()
        {
            writer.WriteLine("""
                             // <auto-generated/>
                             
                             #nullable enable annotations
                             #nullable disable warnings
                             
                             // Suppress warnings about [Obsolete] member usage in generated code.
                             #pragma warning disable CS0612, CS0618

                             """);
            return writer;
        }

        public SourceWriter ForInterceptor()
        {
            writer.PreAmble()
                .WriteLine("""
                           namespace System.Runtime.CompilerServices
                           {
                           """);
            writer.Indentation++;
            writer.WriteLine("""
                             [global::System.Diagnostics.Conditional("DEBUG")]
                             [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                             sealed file class InterceptsLocationAttribute : global::System.Attribute
                             {
                             """);
            writer.Indentation++;
            writer.WriteLine("""
                             public InterceptsLocationAttribute(int version, string data)
                             {
                                 _ = version;
                                 _ = data;
                             }
                             """);
            writer.CloseCurlies();
            writer.WriteLine();
            return writer.WithOpenNamespace("NServiceBus");
        }

        public SourceWriter WithGeneratedCodeAttribute() => writer.WithGeneratedCodeAttribute(AssemblyName);

        public SourceWriter WithGeneratedCodeAttribute(AssemblyName assemblyName)
        {
            writer.WriteLine($"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{assemblyName.Name}", "{assemblyName.Version.ToString(3)}")]""");
            return writer;
        }

        public SourceWriter WithOpenNamespace(string? namespaceName)
        {
            if (string.IsNullOrWhiteSpace(namespaceName))
            {
                return writer;
            }

            writer.WriteLine($"namespace {namespaceName}");
            writer.WriteLine("{");
            writer.Indentation++;
            return writer;
        }

        public void CloseCurlies()
        {
            while (writer.Indentation > 0)
            {
                writer.Indentation--;
                writer.WriteLine("}");
            }
        }
    }

    static readonly AssemblyName AssemblyName = typeof(SourceWriter).Assembly.GetName();
}