#nullable enable

namespace NServiceBus.Core.Analyzer.Utility;

using System.Reflection;

static class SourceWriterExtensions
{
    extension(SourceWriter writer)
    {
        public SourceWriter PreAmble()
        {
            writer.WriteLine("""
                             // <auto-generated/>
                             
                             #nullable enable annotations
                             #nullable disable warnings
                             
                             // Suppress warnings about [Obsolete] member usage in generated code.
                             #pragma warning disable CS0612, CS0618

                             """);
            return writer;
        }

        public SourceWriter ForInterceptor()
        {
            writer.PreAmble();
            return writer.WithFileScopedNamespace("NServiceBus");
        }

        public SourceWriter WithGeneratedCodeAttribute() => writer.WithGeneratedCodeAttribute(AssemblyName);

        public SourceWriter WithGeneratedCodeAttribute(AssemblyName assemblyName)
        {
            writer.WriteLine($"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{assemblyName.Name}", "{assemblyName.Version.ToString(3)}")]""");
            return writer;
        }

        public SourceWriter WithFileScopedNamespace(string? namespaceName)
        {
            if (string.IsNullOrWhiteSpace(namespaceName))
            {
                return writer;
            }

            writer.WriteLine($"namespace {namespaceName};");
            writer.WriteLine();
            return writer;
        }

        public void CloseCurlies()
        {
            while (writer.Indentation > 0)
            {
                writer.Indentation--;
                writer.WriteLine("}");
            }
        }
    }

    static readonly AssemblyName AssemblyName = typeof(SourceWriter).Assembly.GetName();
}
