namespace NServiceBus.Core.Analyzer.Utility;

static class SourceWriterExtensions
{
    extension(SourceWriter writer)
    {
        public SourceWriter PreAmble()
        {
            writer.WriteLine("""
                             // <auto-generated/>
                             #nullable enable

                             """);
            return writer;
        }

        public SourceWriter ForInterceptor()
        {
            writer.PreAmble()
                .WriteLine("""
                           namespace System.Runtime.CompilerServices
                           {
                           """);
            writer.Indentation++;
            writer.WriteLine("""
                             [global::System.Diagnostics.Conditional("DEBUG")]
                             [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                             sealed file class InterceptsLocationAttribute : global::System.Attribute
                             {
                             """);
            writer.Indentation++;
            writer.WriteLine("""
                             public InterceptsLocationAttribute(int version, string data)
                             {
                                 _ = version;
                                 _ = data;
                             }
                             """);
            writer.CloseCurlies();
            writer.WriteLine();
            writer.WriteLine("""
                            namespace NServiceBus
                            {
                            """);
            writer.Indentation++;
            return writer;
        }

        public void CloseCurlies()
        {
            while (writer.Indentation > 0)
            {
                writer.Indentation--;
                writer.WriteLine("}");
            }
        }
    }
}