#nullable enable

namespace NServiceBus.Extensibility;

using System;
using System.ComponentModel;

/// <summary>
/// This attribute is used by source generators to identify type registration classes, so that
/// a final compilation can find and execute the registration methods on all type registration
/// classes.
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed class AutoGeneratedTypeRegistrationsAttribute : Attribute
{
}
