namespace NServiceBus.Extensibility;

using System;
using System.ComponentModel;

/// <summary>
///
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
public sealed class NServiceBusExtensionPointAttribute : Attribute
{
    /// <summary>
    ///
    /// </summary>
    public string RegistrationMethodName { get; init; }

    /// <summary>
    ///
    /// </summary>
    public bool AutoRegister { get; init; }

    /// <summary>
    ///
    /// </summary>
    public NServiceBusExtensionPointAttribute(string registrationMethodName, bool autoRegister)
    {
        RegistrationMethodName = registrationMethodName;
        AutoRegister = autoRegister;
    }
}

/// <summary>
///
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed class AutoGeneratedTypeRegistrationsAttribute : Attribute
{
    /// <summary>
    ///
    /// </summary>
    public bool AutoRegister { get; init; }

    /// <summary>
    ///
    /// </summary>
    /// <param name="autoRegister"></param>
    public AutoGeneratedTypeRegistrationsAttribute(bool autoRegister) => AutoRegister = autoRegister;
}
