#nullable enable

namespace NServiceBus.Core.Analyzer.Messages;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using NServiceBus.Core.Analyzer;

[Generator(LanguageNames.CSharp)]
public sealed partial class AddMessageTypeInterceptor : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var trimmingEnabled = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) => IsPublishTrimmed(options))
            .WithTrackingName(TrackingNames.TrimmingEnabled);

        context.RegisterSourceOutput(trimmingEnabled, static (productionContext, enabled) =>
        {
            if (!enabled)
            {
                return;
            }

            productionContext.AddSource("TrimmingEnabled.g.cs", """
                                                                  // <auto-generated/>
                                                                  [assembly: global::NServiceBus.TrimmingEnabled()]
                                                                  """);
        });

        var addMessageTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => Parser.SyntaxLooksLikeAddMessageTypeMethod(node),
                transform: static (ctx, _) => (invocation: (InvocationExpressionSyntax)ctx.Node, semanticModel: ctx.SemanticModel))
            .Select(static (pair, cancellationToken) =>
            {
                var (invocation, semanticModel) = pair;
                return Parser.Parse(invocation!, semanticModel!, cancellationToken);
            })
            .Where(static spec => spec.HasValue)
            .Select(static (spec, _) => spec!.Value)
            .WithTrackingName(TrackingNames.MessageTypeSpec);

        var collected = addMessageTypes.Collect()
            .Select((specs, _) => new InterceptableMessageTypeSpecs(specs.ToImmutableEquatableArray()))
            .WithTrackingName(TrackingNames.MessageTypeSpecs);

        context.RegisterSourceOutput(collected,
            static (productionContext, spec) =>
            {
                var emitter = new Emitter(productionContext);
                emitter.Emit(spec);
            });
    }

    static bool IsPublishTrimmed(AnalyzerConfigOptionsProvider options) =>
        (options.GlobalOptions.TryGetValue("build_property.PublishTrimmed", out var publishTrimmed) && publishTrimmed == "true") ||
        (options.GlobalOptions.TryGetValue("build_property.PublishAot", out var publishAot) && publishAot == "true");
}
