name: Improvement request
description: Suggest an improvement to an existing code base.
labels: ["Improvement" ]
body:
  - type: markdown
    attributes:
      value: | 
        Please check all open and closed issues to see if improvement has already been suggested.
  - type: textarea
    id: description
    attributes:
      label: Describe the suggested improvement
      description: A clear and concise description of what the improvement is.    
      value: | 
        #### Is your improvement related to a problem? Please describe.
        
        #### Describe the suggested solution
                
        #### Describe alternatives you've considered
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the suggestion here.
      placeholder: "Add screenshots or additional information."
    validations:
      required: false  
  - type: markdown
    attributes:
      value: |        
        For additional support options visit [particular.net/support](https://particular.net/support)
