BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

DROP TABLE dbo.MessageDeduplication
GO

CREATE TABLE dbo.MessageDeduplication
(
	DateTime datetime NOT NULL,
	ClientId varchar(50) NOT NULL,
) ON [PRIMARY]
GO

CREATE CLUSTERED INDEX IX_MessageDeduplication ON dbo.MessageDeduplication
(
	DateTime
) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_MessageDeduplication ON dbo.MessageDeduplication
(
	ClientId
) ON [PRIMARY]
GO

COMMIT