//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NServiceBus.Persistence.Raven.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NServiceBus.Persistence.Raven.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] BouncyCastle_Crypto {
            get {
                object obj = ResourceManager.GetObject("BouncyCastle_Crypto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Esent_Interop {
            get {
                object obj = ResourceManager.GetObject("Esent_Interop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ICSharpCode_NRefactory {
            get {
                object obj = ResourceManager.GetObject("ICSharpCode_NRefactory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lucene_Net {
            get {
                object obj = ResourceManager.GetObject("Lucene_Net", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lucene_Net_Contrib_Spatial {
            get {
                object obj = ResourceManager.GetObject("Lucene_Net_Contrib_Spatial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lucene_Net_Contrib_SpellChecker {
            get {
                object obj = ResourceManager.GetObject("Lucene_Net_Contrib_SpellChecker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NLog {
            get {
                object obj = ResourceManager.GetObject("NLog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Raven_Abstractions {
            get {
                object obj = ResourceManager.GetObject("Raven_Abstractions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Raven_Database {
            get {
                object obj = ResourceManager.GetObject("Raven_Database", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Raven_Munin {
            get {
                object obj = ResourceManager.GetObject("Raven_Munin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Raven_Server {
            get {
                object obj = ResourceManager.GetObject("Raven_Server", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;Raven/Port&quot; value=&quot;*&quot;/&gt;
        ///    &lt;add key=&quot;Raven/DataDir&quot; value=&quot;~\Data&quot;/&gt;
        ///    &lt;add key=&quot;Raven/AnonymousAccess&quot; value=&quot;Get&quot;/&gt;
        ///  &lt;/appSettings&gt;
        ///	&lt;runtime&gt;
        ///		&lt;loadFromRemoteSources enabled=&quot;true&quot;/&gt;
        ///		&lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///			&lt;probing privatePath=&quot;Analyzers&quot;/&gt;
        ///		&lt;/assemblyBinding&gt;
        ///	&lt;/runtime&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string Raven_Server_exe {
            get {
                return ResourceManager.GetString("Raven_Server_exe", resourceCulture);
            }
        }
        
        internal static byte[] Raven_Storage_Esent {
            get {
                object obj = ResourceManager.GetObject("Raven_Storage_Esent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Raven_Storage_Managed {
            get {
                object obj = ResourceManager.GetObject("Raven_Storage_Managed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Raven_Studio {
            get {
                object obj = ResourceManager.GetObject("Raven_Studio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Spatial4n_Core {
            get {
                object obj = ResourceManager.GetObject("Spatial4n_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
