#nullable enable

namespace NServiceBus.Core.Analyzer.Sagas;

using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Utility;

[Generator]
public class AddSagaInterceptor : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var addSagas = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: SyntaxLooksLikeAddSagaMethod,
                transform: TransformInvocation)
            .Where(static d => d is not null)
            .Select(static (d, _) => d!)
            .WithTrackingName("InterceptCandidates");

        var collected = addSagas.Collect()
            .WithTrackingName("Collected");

        context.RegisterSourceOutput(collected, GenerateInterceptorCode);
    }

    static bool SyntaxLooksLikeAddSagaMethod(SyntaxNode node, CancellationToken cancellationToken) => node is InvocationExpressionSyntax
    {
        Expression: MemberAccessExpressionSyntax
        {
            Name: GenericNameSyntax
            {
                Identifier.ValueText: AddSagaMethodName,
                TypeArgumentList.Arguments.Count: 1
            }
        },
        ArgumentList.Arguments.Count: 0
    };

    static InterceptDetails? TransformInvocation(GeneratorSyntaxContext ctx, CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)ctx.Node;

        if (ctx.SemanticModel.GetOperation(invocation, cancellationToken) is not IInvocationOperation operation)
        {
            return null;
        }

        // Make sure the method we're looking at is ours and not some (extremely unlikely) copycat
        if (!IsAddSagaMethod(operation.TargetMethod))
        {
            return null;
        }

        if (operation.TargetMethod.TypeArguments[0] is not INamedTypeSymbol sagaType)
        {
            return null;
        }

        // Extract saga data type from Saga<TSagaData>
        var sagaDataType = GetSagaDataType(sagaType);
        if (sagaDataType == null)
        {
            return null;
        }

        // Get interceptable location for code generation
        if (ctx.SemanticModel.GetInterceptableLocation(invocation, cancellationToken) is not { } location)
        {
            return null;
        }

        var methodName = CreateMethodName(sagaType);
        var sagaFullyQualifiedName = sagaType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var sagaDataFullyQualifiedName = sagaDataType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        return new InterceptDetails(SafeInterceptionLocation.From(location), methodName, sagaFullyQualifiedName, sagaDataFullyQualifiedName);
    }

    static INamedTypeSymbol? GetSagaDataType(INamedTypeSymbol sagaType)
    {
        // Find Saga<TSagaData> in the inheritance chain
        var baseType = sagaType.BaseType;
        while (baseType != null)
        {
            if (baseType is { IsGenericType: true, Name: "Saga", TypeArguments.Length: 1 })
            {
                if (baseType.TypeArguments[0] is INamedTypeSymbol sagaDataType)
                {
                    return sagaDataType;
                }
            }
            baseType = baseType.BaseType;
        }
        return null;
    }

    static string CreateMethodName(INamedTypeSymbol sagaType)
    {
        const string NamePrefix = "AddSaga_";

        var sb = new StringBuilder(NamePrefix, 50)
            .Append(sagaType.Name)
            .Append('_');

        var sagaFullName = sagaType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var hash = NonCryptographicHash.GetHash(sagaFullName);

        sb.Append(hash.ToString("x16"));

        return sb.ToString();
    }

    static bool IsAddSagaMethod(IMethodSymbol method) => method is
    {
        Name: AddSagaMethodName,
        IsGenericMethod: true,
        TypeArguments.Length: 1,
        ContainingType:
        {
            Name: AddSagaClassName,
            ContainingNamespace:
            {
                Name: "NServiceBus",
                ContainingNamespace.IsGlobalNamespace: true
            }
        }
    };

    static void GenerateInterceptorCode(SourceProductionContext context, ImmutableArray<InterceptDetails> intercepts)
    {
        if (intercepts.Length == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("""
                      // <auto-generated/>
                      #nullable enable

                      namespace System.Runtime.CompilerServices
                      {
                          [global::System.Diagnostics.Conditional("DEBUG")]
                          [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                          sealed file class InterceptsLocationAttribute : global::System.Attribute
                          {
                              public InterceptsLocationAttribute(int version, string data)
                              {
                                  _ = version;
                                  _ = data;
                              }
                          }
                      }

                      namespace NServiceBus
                      {
                          static file class InterceptionsOfAddSagaMethod
                          {
                      """);

        var groups = intercepts.GroupBy(i => i.MethodName)
            .OrderBy(g => g.Key, StringComparer.Ordinal);
        foreach (IGrouping<string, InterceptDetails> group in groups)
        {
            foreach (InterceptDetails location in group)
            {
                sb.AppendLine($"        {location.Location.Attribute} // {location.Location.DisplayLocation}");
            }

            InterceptDetails first = group.First();
            sb.AppendLine($$"""
                                    public static void {{first.MethodName}}(this NServiceBus.EndpointConfiguration endpointConfiguration)
                                    {
                                        System.ArgumentNullException.ThrowIfNull(endpointConfiguration);
                                        
                                        var sagaMetadataCollection = NServiceBus.Configuration.AdvancedExtensibility.AdvancedExtensibilityExtensions.GetSettings(endpointConfiguration)
                                            .GetOrCreate<NServiceBus.Sagas.SagaMetadataCollection>();
                                        
                                        var metadata = NServiceBus.Sagas.SagaMetadata.Create<{{first.SagaType}}>();
                                        sagaMetadataCollection.Register(metadata);
                                    }
                            """);
        }

        sb.AppendLine("""
                          }
                      }
                      """);

        context.AddSource("InterceptionsOfAddSagaMethod.g.cs", sb.ToString());
    }

    const string AddSagaClassName = "SagaRegistrationExtensions";
    const string AddSagaMethodName = "AddSaga";

    record InterceptDetails(SafeInterceptionLocation Location, string MethodName, string SagaType, string SagaDataType);
    readonly record struct SafeInterceptionLocation(string Attribute, string DisplayLocation)
    {
        public static SafeInterceptionLocation From(InterceptableLocation location) =>
            new(location.GetInterceptsLocationAttributeSyntax(), location.GetDisplayLocation());
    }
}

