#nullable enable
namespace NServiceBus.Core.Analyzer;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public sealed class KnownTypesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // context.RegisterPostInitializationOutput(ctx =>
        // {
        //     ctx.AddSource("AssemblyScanningOptionsAttribute.g.cs", SourceText.From(SourceGenerationHelper.AssemblyScanningOptionsAttribute, Encoding.UTF8));
        // });

        //context.SyntaxProvider.ForAttributeWithMetadataName()

        var sourceTypes = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is TypeDeclarationSyntax,
            transform: GetTypeFromGeneratorSyntaxContext);

        var collected = sourceTypes.Collect();

        // Instead of RegisterSourceOutput because it doesn't need to be directly called from anything
        // but generated sources - not having it is not going to cause red squigglies
        // https://andrewlock.net/creating-a-source-generator-part-9-avoiding-performance-pitfalls-in-incremental-generators/#7-consider-using-registerimplementationsourceoutput-instead-of-registersourceoutput
        context.RegisterImplementationSourceOutput(collected, (sourceProductionContext, matches) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("""
                          #nullable enable
                          // <auto-generated/>
                          namespace Generated
                          {
                              public static class Registry
                              {
                                  public static readonly System.Type[] Types = new System.Type[]
                                  {
                          """);

            foreach (var type in matches)
            {
                if (type is not null)
                {
                    sb.AppendLine($"            typeof({type.Value.DisplayName}),");
                }
            }

            sb.AppendLine("""
                                  };
                              }
                          }
                          """);

            sourceProductionContext.AddSource("Registry.g.cs", sb.ToString());
        });
    }

    static readonly ImmutableHashSet<TargetType> InterfaceTypeNameObjects =
    [
        new ("NServiceBus", "IEvent"),
        new ("NServiceBus", "ICommand"),
        new ("NServiceBus", "IMessage"),
        new ("NServiceBus", "IHandleMessages`1"),
        new ("NServiceBus.Installation", "INeedToInstallSomething"),
    ];

    static readonly ImmutableHashSet<string> InterfaceTypeNames =
    [
        "NServiceBus.IEvent",
        "NServiceBus.ICommand",
        "NServiceBus.IMessage",
        "NServiceBus.IHandleMessages`1",
        "NServiceBus.Installation.INeedToInstallSomething"
    ];

    record struct TargetType(string Namespace, string Name);

    static ScannedTypeInfo? GetTypeFromGeneratorSyntaxContext(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {

        var symbol = context.SemanticModel.GetDeclaredSymbol(context.Node, cancellationToken);

        if (symbol is not INamedTypeSymbol type)
        {
            return null;
        }

        if (type.IsAnonymousType || type.IsImplicitlyDeclared || type.IsComImport || type.IsUnmanagedType || !type.CanBeReferencedByName)
        {
            return null;
        }

        foreach (var iface in type.AllInterfaces)
        {
            var ifaceName = (iface.ContainingNamespace is not null ? iface.ContainingNamespace?.ToDisplayString() + "." : "") + iface.MetadataName;
            if (InterfaceTypeNames.Contains(ifaceName))
            {
                return new ScannedTypeInfo(type.ToDisplayString());
            }
        }

        // foreach (var iface in type.AllInterfaces)
        // {
        //     foreach (var targetIface in InterfaceTypeNames)
        //     {
        //         if (iface.ContainingNamespace.Name == targetIface.Namespace && iface.MetadataName == targetIface.Name)
        //         {
        //             return new ScannedTypeInfo(type.ToDisplayString());
        //         }
        //     }
        // }

        // if (type.AllInterfaces.Any(i => InterfaceTypeNames.Any(n => i.ContainingNamespace.Name == n.Namespace && i.MetadataName == n.Name)))
        // {
        //
        // }

        return null;
    }

    record struct ScannedTypeInfo(string DisplayName);
}

[Generator]
public sealed class CombinedGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("AssemblyScanningOptionsAttribute.g.cs", SourceText.From(SourceGenerationHelper.AssemblyScanningOptionsAttribute, Encoding.UTF8));
        });

        //context.SyntaxProvider.ForAttributeWithMetadataName()

        var sourceTypes = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is TypeDeclarationSyntax,
            transform: GetTypeFromGeneratorSyntaxContext);

        var metadataTypes = context.CompilationProvider
            .SelectMany((compilation, x) => GetAllTypes(compilation.GlobalNamespace))
            .Select(GetTypeData);

        var collectedSource = sourceTypes.Collect();
        var collectedMetadata = metadataTypes.Collect();

        var combined = collectedSource.Combine(collectedMetadata)
            .Select((tuple, cancellationToken) =>
            {
                var (src, meta) = tuple;
                return src.Concat(meta).ToImmutableArray();
            });

        // Instead of RegisterSourceOutput because it doesn't need to be directly called from anything
        // but generated sources - not having it is not going to cause red squigglies
        // https://andrewlock.net/creating-a-source-generator-part-9-avoiding-performance-pitfalls-in-incremental-generators/#7-consider-using-registerimplementationsourceoutput-instead-of-registersourceoutput
        context.RegisterImplementationSourceOutput(combined, (sourceProductionContext, matches) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("""
                          #nullable enable
                          // <auto-generated/>
                          namespace Generated
                          {
                           public static class Registry
                           {
                               public static readonly string[] Types = new string[]
                               {
                          """);

            foreach (var type in matches)
            {
                if (type is not null)
                {
                    sb.AppendLine($"            \"{type.Value.DisplayName}\",");
                }
            }

            sb.AppendLine("""
                                  };
                              }
                          }
                          """);

            sourceProductionContext.AddSource("Registry.g.cs", sb.ToString());
        });

    }

    static ScannedTypeInfo? GetTypeFromGeneratorSyntaxContext(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var symbol = context.SemanticModel.GetDeclaredSymbol(context.Node, cancellationToken);
        return GetTypeData(symbol as INamedTypeSymbol, cancellationToken);
    }

    static ScannedTypeInfo? GetTypeData(INamedTypeSymbol? type, CancellationToken cancellationToken)
    {
        if (type is null || type.IsAnonymousType || type.IsImplicitlyDeclared || type.IsComImport || type.IsUnmanagedType || !type.CanBeReferencedByName)
        {
            return null;
        }

        if (!(type.ContainingNamespace?.Name.StartsWith("NServiceBus") ?? false))
        {
            return null;
        }

        return new ScannedTypeInfo(type.ToDisplayString());
    }

    static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            yield return type;

            foreach (var nested in GetAllTypes(type))
            {
                yield return nested;
            }
        }

        foreach (var nestedNs in ns.GetNamespaceMembers())
        {
            foreach (var type in GetAllTypes(nestedNs))
            {
                yield return type;
            }
        }
    }

    static IEnumerable<INamedTypeSymbol> GetAllTypes(INamedTypeSymbol type)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            yield return nested;
            foreach (var t in GetAllTypes(nested))
            {
                yield return t;
            }
        }
    }

    record struct ScannedTypeInfo(string DisplayName);
}

public class SourceGenerationHelper
{
    public const string AssemblyScanningOptionsAttribute = "";
}