using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.10.1.0")]
[assembly: AssemblyFileVersionAttribute("1.10.1.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © NServiceBus 2007-2009")]
[assembly: AssemblyProductAttribute("NServiceBus")]
[assembly: AssemblyCompanyAttribute("NServiceBus")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("1.10.1.0")]

