using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("2.1.0.0")]
[assembly: AssemblyFileVersionAttribute("2.1.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © NServiceBus 2007-2009")]
[assembly: AssemblyProductAttribute("NServiceBus")]
[assembly: AssemblyCompanyAttribute("NServiceBus")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("2.1.0.0")]
[assembly: AllowPartiallyTrustedCallersAttribute()]
[assembly: ComVisibleAttribute(false)]

