//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NServiceBus.SQLite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NServiceBus.SQLite.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of SQLite being loaded was compiled against version 2.0.50727 while the current CLR version is 4.0 (or above).  In order to load the assembly, please add the following line to your configuration file.  If you are running NServiceBus.Host,  you will need to add this to a file called NServiceBus.Host.exe.config: &lt;startup useLegacyV2RuntimeActivationPolicy=&quot;true&quot; /&gt;.
        /// </summary>
        internal static string ConfigurationErrorsException {
            get {
                return ResourceManager.GetString("ConfigurationErrorsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed mode assembly.
        /// </summary>
        internal static string MixedModeAssembly {
            get {
                return ResourceManager.GetString("MixedModeAssembly", resourceCulture);
            }
        }
        
        internal static byte[] SQLite32 {
            get {
                object obj = ResourceManager.GetObject("SQLite32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SQLite64 {
            get {
                object obj = ResourceManager.GetObject("SQLite64", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
