name: CI
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
defaults:
  run:
    shell: pwsh
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: Windows
          - os: ubuntu-latest
            name: Linux
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v6.0.0
        with:
          global-json-file: global.json
      - name: Build
        run: dotnet build src --configuration Release
      - name: Upload packages
        if: matrix.name == 'Windows'
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NuGet packages
          path: nugets/
          retention-days: 7
      - name: Run tests
        run: |
          src\NServiceBus.AcceptanceTests\bin\Release\net10.0\NServiceBus.AcceptanceTests.exe --zero-tests-policy strict --report-gh
          src\NServiceBus.Core.Analyzer.Tests.Roslyn5\bin\Release\net10.0\NServiceBus.Core.Analyzer.Tests.Roslyn5.exe --zero-tests-policy strict --report-gh
          src\NServiceBus.Core.Tests\bin\Release\net10.0\NServiceBus.Core.Tests.exe --zero-tests-policy strict --report-gh
          src\NServiceBus.Learning.AcceptanceTests\bin\Release\net10.0\NServiceBus.Learning.AcceptanceTests.exe --zero-tests-policy strict --report-gh
          src\NServiceBus.PersistenceTests\bin\Release\net10.0\NServiceBus.PersistenceTests.exe --zero-tests-policy strict --report-gh
          src\NServiceBus.TransportTests\bin\Release\net10.0\NServiceBus.TransportTests.exe --zero-tests-policy strict --report-gh

